#!/bin/bash

#set environment variables
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT=${1:-"/home/executeASIMSpec.sh"}

#get os
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Win;;
    MINGW*)     machine=Win;;
    *)          machine="UNKNOWN:${unameOut}"
esac

#fix path for windows
if [ "$machine" == "Win" ]
then
  #fix path
  WINDIR="${DIR//\//\\}"
  WINDIR="${WINDIR/\\c/C:}"
  
  #export to fix path mangling bug
  export MSYS_NO_PATHCONV=1
  winpty bash $DIR/scripts/runDocker.sh $WINDIR /$SCRIPT
  export MSYS_NO_PATHCONV=0
else
  $DIR/scripts/runDocker.sh $DIR $SCRIPT
fi

#remove stale container if exists
docker rm active_asim 2>/dev/null
